version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017/shop?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
