version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:pa$$word@mongo:27017/
      - MONGO_DB=shop
      - JWT_SECRET=bitsshop

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pa$$word
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
