version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/shop?authSource=admin
      - JWT_SECRET=bitsshop

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=shop
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
